; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#ifndef MyAppVersion
#define MyAppVersion "v2.7.2.1"
#endif

#define MyAppBinDir "..\AudiobookshelfTray\bin\x64\Release\net461"
#define ServiceBinDir "..\AudiobookshelfService\bin\x64\Release\net461"
#define ServerBinDir "..\..\audiobookshelf\dist\win"


#define MyAppName "Audiobookshelf"
#define MyAppPublisher "Audiobookshelf"
#define MyAppURL "https://www.audiobookshelf.org/"
#define MyAppExeName "AudiobookshelfTray.exe"
#define ServiceExeName "AudiobookshelfService.exe"
#define ServerExeName "audiobookshelf.exe"
#define ServiceName "AudiobookshelfService"

[Setup]
AppId={{398D8732-4648-4C71-A30C-C0688D46BB13}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputBaseFilename=AudiobookshelfInstaller
SetupIconFile=..\AudiobookshelfTray\Resources\AppIcon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppBinDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppBinDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ServiceBinDir}\{#ServiceExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ServiceBinDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ServerBinDir}\{#ServerExeName}"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; 1. Create the Windows Service (if not bypassed)
Filename: "{sys}\sc.exe"; Parameters: "create {#ServiceName} binPath= ""{app}\{#ServiceExeName}"" start= auto DisplayName= ""Audiobookshelf Service"""; Flags: runhidden; Check: ShouldInstallService
; 2. Set service description
Filename: "{sys}\sc.exe"; Parameters: "description {#ServiceName} ""Audiobookshelf Background Server and Network Drive Supervisor"""; Flags: runhidden; Check: ShouldInstallService
; 3. Configure service user account if provided
Filename: "{sys}\sc.exe"; Parameters: "config {#ServiceName} obj= ""{code:GetServiceUsername}"" password= ""{code:GetServicePassword}"""; Flags: runhidden; Check: HasUserCredentials
; 4. Grant start/stop/control service permissions ONLY to the configured service user account (and SY/BA)
Filename: "{sys}\sc.exe"; Parameters: "sdset {#ServiceName} ""{code:GetServiceDacl}"""; Flags: runhidden; Check: ShouldInstallService
; 5. Add Windows Firewall Inbound Rule
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName} Server"" dir=in action=allow protocol=TCP localport={code:GetServerPort} profile=any description=""Allow inbound connections for Audiobookshelf Server"""; Flags: runhidden; Check: ShouldConfigureFirewall
; 6. Start the service
Filename: "{sys}\net.exe"; Parameters: "start {#ServiceName}"; Flags: runhidden; Check: ShouldInstallService
; 7. Launch Tray application
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall

[UninstallRun]
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName} Server"""; Flags: runhidden; RunOnceId: "DeleteFirewallRule"
Filename: "{sys}\sc.exe"; Parameters: "stop {#ServiceName}"; Flags: runhidden; RunOnceId: "StopService"
Filename: "{sys}\taskkill.exe"; Parameters: "/F /IM {#ServiceExeName} /IM {#ServerExeName} /IM {#MyAppExeName}"; Flags: runhidden; RunOnceId: "KillProcesses"
Filename: "{sys}\sc.exe"; Parameters: "delete {#ServiceName}"; Flags: runhidden; RunOnceId: "DeleteService"

[UninstallDelete]
Type: files; Name: "{app}\*.bak"
Type: files; Name: "{app}\*.log"

[Registry]
Root: HKLM; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "DataDir"; ValueData: "{code:GetDataDir}"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "AppVersion"; ValueData: "{#MyAppVersion}"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "ServerPort"; ValueData: "{code:GetServerPort}"; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "ServerHost"; ValueData: "{code:GetServerHost}"; Flags: uninsdeletevalue

[Code]
// Win32 Authentication APIs
function LogonUser(
  lpszUsername: String;
  lpszDomain: String;
  lpszPassword: String;
  dwLogonType: DWORD;
  dwLogonProvider: DWORD;
  var phToken: THandle
): Boolean;
external 'LogonUserW@advapi32.dll stdcall';

function CloseHandle(hObject: THandle): Boolean;
external 'CloseHandle@kernel32.dll stdcall';

var
  DataDirPage: TInputDirWizardPage;
  ServicePage: TWizardPage;
  InstallServiceCheck: TCheckBox;
  UserLabel, PassLabel, NoteLabel: TLabel;
  UserEdit, PassEdit: TEdit;

const
  WM_CLOSE = $0010;

function HasCmdSwitch(SwitchName: String): Boolean;
var
  i: Integer;
  Arg: String;
  Target: String;
begin
  Result := False;
  Target := UpperCase(SwitchName);
  for i := 1 to ParamCount do
  begin
    Arg := UpperCase(ParamStr(i));
    if (Arg = '/' + Target) or (Arg = '-' + Target) or (Arg = '--' + Target) then
    begin
      Result := True;
      Exit;
    end;
  end;
end;

function GetCmdParamValue(ParamName, DefaultVal: String): String;
var
  Val: String;
begin
  Val := ExpandConstant('{param:' + ParamName + '|' + DefaultVal + '}');
  Result := Val;
end;

function GetServerPort(Param: String): String;
var
  PortVal: String;
begin
  PortVal := GetCmdParamValue('PORT', '');
  if Length(PortVal) = 0 then
  begin
    if not RegQueryStringValue(HKLM, 'Software\{#MyAppName}', 'ServerPort', PortVal) then
    begin
      PortVal := '13378';
    end;
  end;
  Result := Trim(PortVal);
end;

function GetServerHost(Param: String): String;
var
  HostVal: String;
begin
  HostVal := GetCmdParamValue('HOST', '');
  if Length(HostVal) = 0 then
  begin
    if not RegQueryStringValue(HKLM, 'Software\{#MyAppName}', 'ServerHost', HostVal) then
    begin
      HostVal := '0.0.0.0';
    end;
  end;
  Result := Trim(HostVal);
end;

function ShouldConfigureFirewall(): Boolean;
var
  FwVal: String;
begin
  if HasCmdSwitch('NOFIREWALL') then
  begin
    Result := False;
    Exit;
  end;

  FwVal := UpperCase(GetCmdParamValue('FIREWALL', '1'));
  if (FwVal = '0') or (FwVal = 'NO') or (FwVal = 'FALSE') then
  begin
    Result := False;
    Exit;
  end;

  Result := True;
end;

function ShouldInstallService(): Boolean;
var
  ParamVal: String;
begin
  if HasCmdSwitch('NOSERVICE') then
  begin
    Result := False;
    Exit;
  end;

  ParamVal := UpperCase(GetCmdParamValue('INSTALLSERVICE', ''));
  if (ParamVal = '0') or (ParamVal = 'NO') or (ParamVal = 'FALSE') then
  begin
    Result := False;
    Exit;
  end;
  if (ParamVal = '1') or (ParamVal = 'YES') or (ParamVal = 'TRUE') then
  begin
    Result := True;
    Exit;
  end;

  if InstallServiceCheck <> nil then
  begin
    Result := InstallServiceCheck.Checked;
  end
  else
  begin
    Result := True;
  end;
end;

function GetDataDir(Param: String): String;
var
  CliDataDir: String;
begin
  CliDataDir := GetCmdParamValue('DATADIR', '');
  if Length(CliDataDir) > 0 then
  begin
    Result := CliDataDir;
    Exit;
  end;

  if (DataDirPage <> nil) and (Length(DataDirPage.Values[0]) > 0) then
  begin
    Result := DataDirPage.Values[0];
  end
  else
  begin
    Result := ExpandConstant('{commonappdata}\{#MyAppName}');
  end;
end;

function GetServiceUsername(Param: String): String;
var
  UserVal: String;
begin
  UserVal := GetCmdParamValue('SERVICE_USER', '');
  if Length(UserVal) = 0 then UserVal := GetCmdParamValue('USER', '');
  if (Length(UserVal) = 0) and (UserEdit <> nil) then
  begin
    UserVal := UserEdit.Text;
  end;
  Result := Trim(UserVal);
end;

function GetServicePassword(Param: String): String;
var
  PassVal: String;
begin
  PassVal := GetCmdParamValue('SERVICE_PASS', '');
  if Length(PassVal) = 0 then PassVal := GetCmdParamValue('PASSWORD', '');
  if Length(PassVal) = 0 then PassVal := GetCmdParamValue('PASS', '');
  if (Length(PassVal) = 0) and (PassEdit <> nil) then
  begin
    PassVal := PassEdit.Text;
  end;
  Result := PassVal;
end;

function HasUserCredentials(): Boolean;
begin
  Result := ShouldInstallService() and (Length(GetServiceUsername('')) > 0);
end;

function IsRunningInstanceClosed(): Boolean;
var
  Wnd: HWND;
  ResultCode: Integer;
begin
  // Stop running tray app if open
  Wnd := FindWindowByWindowName('AudiobookshelfTray');
  if Wnd <> 0 then
  begin
    SendMessage(Wnd, WM_CLOSE, 0, 0);
  end;

  // Stop running service if present
  Exec(ExpandConstant('{sys}\sc.exe'), 'stop {#ServiceName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  Result := True;
end;

function InitializeSetup(): Boolean;
var
  Version: TWindowsVersion;
begin
  GetWindowsVersionEx(Version);
  if (not IsWin64) or (Version.Major < 10) then
  begin
    MsgBox('{#MyAppName} requires 64-bit Windows 10 or later.', mbError, MB_OK);
    Result := False;
    Exit;
  end;

  if not IsRunningInstanceClosed() then
  begin
    Result := False;
    Exit;
  end;

  Result := True;
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  // Remove firewall rule, stop running service, and terminate processes to prevent locked file errors during uninstall
  Exec(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall delete rule name="{#MyAppName} Server"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec(ExpandConstant('{sys}\sc.exe'), 'stop {#ServiceName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#ServiceExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#ServerExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec(ExpandConstant('{sys}\sc.exe'), 'delete {#ServiceName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  Result := True;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
begin
  if CurUninstallStep = usUninstall then
  begin
    // 1. Remove Windows Firewall rule
    Exec(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall delete rule name="{#MyAppName} Server"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

    // 2. Stop service and terminate any remaining processes
    Exec(ExpandConstant('{sys}\sc.exe'), 'stop {#ServiceName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#ServiceExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#ServerExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Sleep(500);

    // 3. Delete the Windows Service from Service Control Manager
    Exec(ExpandConstant('{sys}\sc.exe'), 'delete {#ServiceName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Sleep(500);
  end;
end;

procedure InstallServiceCheckClick(Sender: TObject);
begin
  UserLabel.Enabled := InstallServiceCheck.Checked;
  UserEdit.Enabled := InstallServiceCheck.Checked;
  PassLabel.Enabled := InstallServiceCheck.Checked;
  PassEdit.Enabled := InstallServiceCheck.Checked;
  NoteLabel.Enabled := InstallServiceCheck.Checked;
end;

procedure InitializeWizard;
var
  DataDir: String;
  CliUser, CliPass, CliDataDir: String;
begin
  // 1. Data Directory Page
  DataDirPage := CreateInputDirPage(
    wpSelectDir, 
    'Select Data Directory', 
    'Where should Audiobookshelf store its data and configuration?', 
    'Select the directory for Audiobookshelf data (default: C:\ProgramData\Audiobookshelf), then click Next.', 
    False, 
    ''
  );
  DataDirPage.Add('');
  DataDirPage.Values[0] := ExpandConstant('{commonappdata}\Audiobookshelf');

  CliDataDir := GetCmdParamValue('DATADIR', '');
  if Length(CliDataDir) > 0 then
  begin
    DataDirPage.Values[0] := CliDataDir;
  end
  else if RegQueryStringValue(HKLM, 'Software\Audiobookshelf', 'DataDir', DataDir) then
  begin
    DataDirPage.Values[0] := DataDir;
  end;

  // 2. Service Installation & Account Options Page
  ServicePage := CreateCustomPage(
    DataDirPage.ID,
    'Windows Service & Account Options',
    'Configure background service installation and network drive credentials'
  );

  // Checkbox to install or bypass the Windows Service
  InstallServiceCheck := TCheckBox.Create(ServicePage);
  InstallServiceCheck.Parent := ServicePage.Surface;
  InstallServiceCheck.Caption := 'Install Audiobookshelf as a background Windows Service (Recommended)';
  InstallServiceCheck.Left := ScaleX(0);
  InstallServiceCheck.Top := ScaleY(5);
  InstallServiceCheck.Width := ServicePage.SurfaceWidth;
  InstallServiceCheck.Font.Style := [fsBold];
  InstallServiceCheck.Checked := ShouldInstallService();
  InstallServiceCheck.OnClick := @InstallServiceCheckClick;

  NoteLabel := TLabel.Create(ServicePage);
  NoteLabel.Parent := ServicePage.Surface;
  NoteLabel.Caption := 'Windows user credentials are required to run the service so it can authenticate and mount network drives (e.g. Z:\):';
  NoteLabel.Left := ScaleX(0);
  NoteLabel.Top := ScaleY(35);
  NoteLabel.Width := ServicePage.SurfaceWidth;
  NoteLabel.WordWrap := True;

  UserLabel := TLabel.Create(ServicePage);
  UserLabel.Parent := ServicePage.Surface;
  UserLabel.Caption := 'Windows Username (e.g. .\Username or DOMAIN\Username):';
  UserLabel.Left := ScaleX(0);
  UserLabel.Top := ScaleY(80);

  UserEdit := TEdit.Create(ServicePage);
  UserEdit.Parent := ServicePage.Surface;
  UserEdit.Left := ScaleX(0);
  UserEdit.Top := ScaleY(100);
  UserEdit.Width := ScaleX(320);

  CliUser := GetCmdParamValue('SERVICE_USER', '');
  if Length(CliUser) = 0 then CliUser := GetCmdParamValue('USER', '');
  if Length(CliUser) > 0 then
    UserEdit.Text := CliUser
  else
    UserEdit.Text := '.\' + GetUserNameString;

  PassLabel := TLabel.Create(ServicePage);
  PassLabel.Parent := ServicePage.Surface;
  PassLabel.Caption := 'Windows Password:';
  PassLabel.Left := ScaleX(0);
  PassLabel.Top := ScaleY(135);

  PassEdit := TEdit.Create(ServicePage);
  PassEdit.Parent := ServicePage.Surface;
  PassEdit.PasswordChar := '*';
  PassEdit.Left := ScaleX(0);
  PassEdit.Top := ScaleY(155);
  PassEdit.Width := ScaleX(320);

  CliPass := GetCmdParamValue('SERVICE_PASS', '');
  if Length(CliPass) = 0 then CliPass := GetCmdParamValue('PASSWORD', '');
  if Length(CliPass) = 0 then CliPass := GetCmdParamValue('PASS', '');
  if Length(CliPass) > 0 then
    PassEdit.Text := CliPass;

  InstallServiceCheckClick(nil);
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  hToken: THandle;
  FullUser, User, Domain, Pass: String;
  SlashPos: Integer;
begin
  Result := True;

  if (ServicePage <> nil) and (CurPageID = ServicePage.ID) then
  begin
    // If user bypassed service install, warn that drive mapping and updates will not work
    if not ShouldInstallService() then
    begin
      if MsgBox('Warning: You have chosen not to install the Audiobookshelf Windows Service.'#13#10#13#10 +
                'Without the background Windows Service:'#13#10 +
                ' • Network drive mappings will not be mounted automatically.'#13#10 +
                ' • Scheduled background updates and pre-update backups will be disabled.'#13#10#13#10 +
                'Are you sure you want to continue without installing the Windows Service?',
                mbConfirmation, MB_YESNO) = IDNO then
      begin
        Result := False;
        Exit;
      end;
      Exit;
    end;

    FullUser := Trim(UserEdit.Text);
    Pass := PassEdit.Text;

    // Credentials are required for network drive access
    if (Length(FullUser) = 0) or (Length(Pass) = 0) then
    begin
      MsgBox('Windows user credentials (Username and Password) are required to install the service.'#13#10#13#10 +
             'The service requires account credentials to authenticate and mount network drives on startup.'#13#10#13#10 +
             'Please enter your Windows password or uncheck the service install option.', mbError, MB_OK);
      Result := False;
      Exit;
    end;

    // Parse Domain and Username
    SlashPos := Pos('\', FullUser);
    if SlashPos > 0 then
    begin
      Domain := Copy(FullUser, 1, SlashPos - 1);
      User := Copy(FullUser, SlashPos + 1, Length(FullUser));
    end
    else
    begin
      Domain := '.';
      User := FullUser;
    end;

    // Validate credentials against Windows LSA
    hToken := 0;
    // LOGON32_LOGON_NETWORK = 3, LOGON32_PROVIDER_DEFAULT = 0
    if not LogonUser(User, Domain, Pass, 3, 0, hToken) then
    begin
      // Fallback: try LOGON32_LOGON_INTERACTIVE = 2
      if not LogonUser(User, Domain, Pass, 2, 0, hToken) then
      begin
        MsgBox('Windows authentication failed.'#13#10#13#10 +
               'The username or password you entered is incorrect.'#13#10 +
               'Please verify your credentials or uncheck the service install option.', mbError, MB_OK);
        Result := False;
        Exit;
      end;
    end;

    if hToken <> 0 then
    begin
      CloseHandle(hToken);
    end;
  end;
end;

function GetServiceUserSid(Param: String): String;
var
  FullUser: String;
  TempFile: String;
  ResultCode: Integer;
  Lines: TArrayOfString;
begin
  Result := '';
  FullUser := GetServiceUsername('');
  if Pos('.\', FullUser) = 1 then
  begin
    FullUser := Copy(FullUser, 3, Length(FullUser));
  end;

  TempFile := ExpandConstant('{tmp}\abs_sid.txt');
  if FileExists(TempFile) then DeleteFile(TempFile);

  Exec('powershell.exe', 
       '-NoProfile -NonInteractive -ExecutionPolicy Bypass -Command ' +
       '"try { $u = ''' + FullUser + '''; $s = (New-Object System.Security.Principal.NTAccount($u)).Translate([System.Security.Principal.SecurityIdentifier]).Value; Set-Content -Path ''' + TempFile + ''' -Value $s } catch { }"',
       '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  if FileExists(TempFile) then
  begin
    if LoadStringsFromFile(TempFile, Lines) and (GetArrayLength(Lines) > 0) then
    begin
      Result := Trim(Lines[0]);
    end;
    DeleteFile(TempFile);
  end;
end;

function GetServiceDacl(Param: String): String;
var
  Sid: String;
begin
  Sid := GetServiceUserSid('');
  if Length(Sid) > 0 then
  begin
    Result := 'D:(A;;CCLCSWRPWPDTLORC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWRPWPDTLORC;;;' + Sid + ')';
  end
  else
  begin
    Result := 'D:(A;;CCLCSWRPWPDTLORC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)';
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  DataDir, EscapedDataDir, ConfigPath, Port, Host: String;
  Lines: TArrayOfString;
begin
  if CurStep = ssPostInstall then
  begin
    DataDir := GetDataDir('');
    if not DirExists(DataDir) then
    begin
      ForceDirectories(DataDir);
    end;

    Port := GetServerPort('');
    Host := GetServerHost('');
    ConfigPath := ExpandConstant('{commonappdata}\{#MyAppName}\config.json');

    // If config.json doesn't exist yet, generate initial config with selected settings
    if not FileExists(ConfigPath) then
    begin
      ForceDirectories(ExtractFileDir(ConfigPath));
      EscapedDataDir := DataDir;
      StringChange(EscapedDataDir, '\', '\\');

      SetArrayLength(Lines, 6);
      Lines[0] := '{';
      Lines[1] := '  "ServerPort": "' + Port + '",';
      Lines[2] := '  "ServerHost": "' + Host + '",';
      Lines[3] := '  "DataDir": "' + EscapedDataDir + '",';
      Lines[4] := '  "AppVersion": "{#MyAppVersion}"';
      Lines[5] := '}';
      SaveStringsToFile(ConfigPath, Lines, False);
    end;
  end;
end;